INSERT ActivityTypes (Name)
VALUES ('Violin First Position Fingerings - Easy'),
		('Viola First Position Fingerings - Easy'),
		('Cello First Position Fingerings - Easy'),
		('Bass First Position Fingerings - Easy')
		--('Violin First Position Fingerings - Challenging'),
		--('Viola First Position Fingerings - Challenging'),
		--('Cello First Position Fingerings - Challenging'),
		--('Bass First Position Fingerings - Challening');
GO

INSERT ProblemModels (Name, CorrectAnswer, QuestionText, PointsPossible, ActivityTypeId)
VALUES ('VlnFirstOpenG', '0', 'How many fingers are needed to play G on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstGstringA', '1', 'How many fingers are needed to play A on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstGstringB', '2', 'How many fingers are needed to play B on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstGstringC', '3', 'How many fingers are needed to play C on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstGstringD', '4', 'How many fingers are needed to play D on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstOpenD', '0', 'How many fingers are needed to play D on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstDstringE', '1', 'How many fingers are needed to play E on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstDStringF#', '2', 'How many fingers are needed to play F# on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstDStringG', '3', 'How many fingers are needed to play G on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstDStringA', '4', 'How many fingers are needed to play A on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstOpenA', '0', 'How many fingers are needed to play A on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstAstringB', '1', 'How many fingers are needed to play B on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstAstringC#', '2', 'How many fingers are needed to play C# on the A string?', 5, 
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstAstringD', '3', 'How many fingers are needed to play D on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstAstringE', '4', 'How many fingers are needed to play E on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstOpenE', '0', 'How many fingers are needed to play E on the E string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstEstringF#', '1', 'How many fingers are needed to play F# on the E string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstEstringG', '2', 'How many fingers are needed to play G on the E string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstEstringA', '3', 'How many fingers are needed to play A on the E string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlnFirstEstringB', '4', 'How many fingers are needed to play B on the E string?', 5,
			(SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('VlaFirstOpenC', '0', 'How many fingers are needed to play C on the C string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstCstringD', '1', 'How many fingers are needed to play D on the C string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstCstringE', '2', 'How many fingers are needed to play E on the C string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstCstringF', '3', 'How many fingers are needed to play F on the C string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstCstringG', '4', 'How many fingers are needed to play G on the C string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstOpenG', '0', 'How many fingers are needed to play G on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstGstringA', '1', 'How many fingers are needed to play A on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstGstringB', '2', 'How many fingers are needed to play B on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstGstringC', '3', 'How many fingers are needed to play C on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstGstringD', '4', 'How many fingers are needed to play D on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstOpenD', '0', 'How many fingers are needed to play D on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstDstringE', '1', 'How many fingers are needed to play E on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstDstringF#', '2', 'How many fingers are needed to play F# on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstDstringG', '3', 'How many fingers are needed to play G on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstDstringA', '4', 'How many fingers are needed to play A on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstOpenA', '0', 'How many fingers are needed to play A on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstAstringB', '1', 'How many fingers are needed to play B on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstAstringC#', '2', 'How many fingers are needed to play C# on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstAstringD', '3', 'How many fingers are needed to play D on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VlaFirstAstringE', '4', 'How many fingers are needed to play E on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('VclFirstOpenC', '0', 'How many fingers are needed to play C on the C string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstCstringD', '1', 'How many fingers are needed to play D on the C string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstCstringE', '3', 'How many fingers are needed to play E on the C string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstCstringF', '4', 'How many fingers are needed to play F on the C string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstOpenG', '0', 'How many fingers are needed to play G on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstGstringA', '1', 'How many fingers are needed to play A on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstGstringB', '3', 'How many fingers are needed to play B on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstGstringC', '4', 'How many fingers are needed to play C on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstOpenD', '0', 'How many fingers are needed to play D on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstDstringE', '1', 'How many fingers are needed to play E on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstDstringF#', '3', 'How many fingers are needed to play F# on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstDstringG', '4', 'How many fingers are needed to play G on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstOpenA', '0', 'How many fingers are needed to play A on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstAstringB', '1', 'How many fingers are needed to play B on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstAstringC#', '3', 'How many fingers are needed to play C# on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('VclFirstAstringD', '4', 'How many fingers are needed to play D on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('BsFirstOpenE', '0', 'How many fingers are needed to play E on the E string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstEstringF#', '1', 'How many fingers are needed to play F# on the E string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstEstringG', '2', 'How many fingers are needed to play G on the E string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstOpenA', '0', 'How many fingers are needed to play A on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstAstringB', '1', 'How many fingers are needed to play B on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstAstringC', '2', 'How many fingers are needed to play C on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstAstringC#', '4', 'How many fingers are needed to play C# on the A string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstOpenD', '0', 'How many fingers are needed to play D on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstDstringE', '1', 'How many fingers are needed to play E on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstDstringF#', '4', 'How many fingers are needed to play F# on the D string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstOpenG', '0', 'How many fingers are needed to play G on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstGstringA', '1', 'How many fingers are needed to play A on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsFirstGstringB', '4', 'How many fingers are needed to play B on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsThirdGstringC', '1', 'How many fingers are needed to play C in third position on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsThirdGstringC#', '2', 'How many fingers are needed to play C# in third position on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('BsThirdGstringD', '4', 'How many fingers are needed to play D in third position on the G string?', 5,
			(SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy'));
GO

INSERT Answers (Selection, ActivityTypeId)
VALUES ('1', (SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('2', (SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('3', (SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('4', (SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('0', (SELECT Id from ActivityTypes where name = 'Violin First Position Fingerings - Easy')),
		('1', (SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('2', (SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('3', (SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('4', (SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('0', (SELECT Id from ActivityTypes where name = 'Viola First Position Fingerings - Easy')),
		('1', (SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('2', (SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('3', (SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('4', (SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('0', (SELECT Id from ActivityTypes where name = 'Cello First Position Fingerings - Easy')),
		('1', (SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('2', (SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('4', (SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy')),
		('0', (SELECT Id from ActivityTypes where name = 'Bass First Position Fingerings - Easy'));
GO	